server:
  # 端口
  port: 8082
spring:
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.163.com
    # 协议
    protocol: smtp
    # 编码格式
    default-encoding: utf-8
    # 授权码（在邮箱开通服务时获取）
    password: CQCRRPRPFIXTOPXK
    # 发送者邮箱地址
    username: l114409962@163.com
    # 端口（不同邮箱端口号不同）
    port: 25

    # rabbitmq配置
  rabbitmq:
      # 用户名
    username: yihengli
      # 密码
    password: l46023424
      # 服务器地址
    host: 192.168.30.229
      # 端口
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual

  redis:
          #超时时间
    timeout: 10000ms
    host: 192.168.30.229
    port: 6379
    password: l46023424
    database: 0
    lettuce:
      pool:
        #最大连接数
        max-active: 1024
        #最大连接阻塞等待时间
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5